language: node_js

sudo: false

cache:
  apt: true
  directories:
    - nodemodules

node_js: stable

install:
  - npm install -D

scripts:
  - node test

notifications:
  webhooks:  http://nimunj.natappfree.cc/travis


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $Travis_token # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master