language: node_js

sudo: false

cache:
  apt: true
  directories:
    - nodemodules

node_js: stable

install:
  - npm install -D

scripts:
  - node test

notifications:
  webhooks:
    - https://oapi.dingtalk.com/robot/send?access_token=1a6e351e35fc4b9690abcbc4ba48f388fa2b878bc0c8052d7813c81c214ea874
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"