language: node_js

sudo: false

cache:
  apt: true
  directories:
    - nodemodules

node_js: stable

install:
  - npm install -D

scripts:
  - node test

notifications:
  webhooks:  http://nimunj.natappfree.cc/travis


# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $Travis_token # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master

after_success:
  - cd ./dist
  - git init
  # - git config --global user.name "${gitee_name}"
  # - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force master master:${P_BRANCH}/${gitee_token}${gitee_ssh} 

# branches:
#   only:
#     - master